### ISSUE TITLE
Erro no número do cartão

### ISSUE THREAD

**Issue by zaninijunior** [marcos-alexandre82/integration-rede-for-woocommerce#2]
Marcos, será que você pode me ajudar?
Alguns clientes tem relatado que quando eles clicam em finalizar a compra aparece o erro que o número do cartão é inválido.

**Comment by marcos-alexandre82** [comment]
Olá,

Consegue verificar se as bandeiras destes cartões estão habilitadas na conta da Rede e se o tipo de cartão (nacional/internacional) também está?

Se conseguir contato com a Rede, tente verificar se eles tem alguma informação sobre, aí me envia aqui para tentarmos solucionar ;)

**Comment by zaninijunior** [comment]
Legal, eu tenho um bom relacionamento com eles sim, vou levantar essas informações. E volto a falar aqui.

**Comment by zaninijunior** [comment]
Tem um outro comportamento estranho. o Woocommerce registra o pedido e fica como pagamento pendente mas nas infos do cartão não tem nada.
Aí o pagamento não acontece.

<img width="875" alt="Captura de Tela 2020-05-17 às 23 19 46" src="https://user-images.githubusercontent.com/9435251/82168539-5a414f00-9895-11ea-9ac4-567c6485563e.png">

**Comment by zaninijunior** [comment]
Marcos, nos logs do Woocommerce achei isso aqui:

2020-05-22T11:45:53+00:00 CRITICAL Uncaught Error: Call to undefined method WP_Post::get_id() in /home/wp_hpf38e/bordadoingles.com.br/wp-content/plugins/woo-rede/integration-rede-for-woocommerce.php:193
Stack trace:
#0 /home/wp_hpf38e/bordadoingles.com.br/wp-includes/class-wp-hook.php(287): update_rede_orders()
#1 /home/wp_hpf38e/bordadoingles.com.br/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#2 /home/wp_hpf38e/bordadoingles.com.br/wp-includes/plugin.php(544): WP_Hook->do_action(Array)
#3 /home/wp_hpf38e/bordadoingles.com.br/wp-cron.php(138): do_action_ref_array('update_rede_ord...', Array)
#4 {main}
  thrown, em /home/wp_hpf38e/bordadoingles.com.br/wp-content/plugins/woo-rede/integration-rede-for-woocommerce.php, na linha 193

**Comment by marcos-alexandre82** [comment]
Fiz uma atualização para tentar resolver este erro do log. Se puder testar e me dar um feedback, agradeço.

Com relação ao print, isso ocorre quando o cartão não é autorizado. No log do plugin, deve ter uma resposta com o status 400.

**Comment by zaninijunior** [comment]
Oi Marcos, obrigado pelas contribuições, você ajuda muito.

O print do "Pagamento Pendente" eu entendi.

Já atualizei o plugin e vou acompanhar os pedidos e os logs.
Volto aqui daqui uns dias para te falar como está.

**Comment by zaninijunior** [comment]
Marcos, o plugin tem funcionado perfeitamente.
Muito obrigado com as suas contribuições.
