### ISSUE TITLE
Configurações do Parceiro

### ISSUE THREAD

**Issue by Gleder10** [marcos-alexandre82/integration-rede-for-woocommerce#4]
Bom dia Marcos Tudo Bem !
Estou configurando o pluggin da Rede
E não sei como pegar as Configurações da Rede
Já me cadastrei no site Da Rede e até agora
não Achei nada.
Poderia me ajudar.
Obrigado

**Comment by marcos-alexandre82** [comment]
Olá,

Você seguiu o guia de instalação?
https://br.wordpress.org/plugins/woo-rede/#installation

Se for dados do ambiente de Produção, precisa entrar em contato com eles e contratar o serviço deles, ;)

**Comment by Gleder10** [comment]
Bom Dia Marco !
Tudo Bem?
A parte de Produção funcinou, para mim o cliente me deu as api's
e deu certo.

É que eu estava querendo fazer funcionar no ambiente de teste e precisava ver
como fazia para ter as informacoes do
Configurações do parceiro
ID do modulo
id do gateway

eu fiz o cadastro e não achei as informacoes acima.
 
Atenciosamente,
Gleder Lourenzoti
Ad Instar Systems Informatica
11-2950-5140 11-29590015 11-999727008

 
 



De: "Marcos Alexandre" <notifications@github.com>
Enviada: 2020/06/11 01:09:30
Para: integration-rede-for-woocommerce@noreply.github.com
Cc:  adinstar@uol.com.br, author@noreply.github.com
Assunto:  Re: [marcos-alexandre82/integration-rede-for-woocommerce] Configurações do Parceiro (#4)
 

 

Olá,

Você seguiu o guia de instalação?
https://br.wordpress.org/plugins/woo-rede/#installation

Se for dados do ambiente de Produção, precisa entrar em contato com eles e contratar o serviço deles, ;)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/marcos-alexandre82/integration-rede-for-woocommerce/issues/4#issuecomment-642393911", "url": "https://github.com/marcos-alexandre82/integration-rede-for-woocommerce/issues/4#issuecomment-642393911", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by marcos-alexandre82** [comment]
Você precisa acessar o painel de desenvolvedor e "criar uma loja":
https://www.userede.com.br/desenvolvedores/pt/loja

Escolhendo a opção "e.Rede"
https://prnt.sc/sy59ib

**Comment by Gleder10** [comment]
Bom dia Marco,

Muitissimo obrigado !


 
Atenciosamente,
Gleder Lourenzoti
Ad Instar Systems Informatica
11-2950-5140 11-29590015 11-999727008

 
 



De: "Marcos Alexandre" <notifications@github.com>
Enviada: 2020/06/11 17:51:56
Para: integration-rede-for-woocommerce@noreply.github.com
Cc:  adinstar@uol.com.br, author@noreply.github.com
Assunto:  Re: [marcos-alexandre82/integration-rede-for-woocommerce] Configurações do Parceiro (#4)
 

 

Você precisa acessar o painel de desenvolvedor e "criar uma loja":
https://www.userede.com.br/desenvolvedores/pt/loja

Escolhendo a opção "e.Rede"
https://prnt.sc/sy59ib

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/marcos-alexandre82/integration-rede-for-woocommerce/issues/4#issuecomment-642921988", "url": "https://github.com/marcos-alexandre82/integration-rede-for-woocommerce/issues/4#issuecomment-642921988", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
