### ISSUE TITLE
Pequenos ajustes

### ISSUE THREAD

**Issue by kaoecoito** [marcos-alexandre82/integration-rede-for-woocommerce#8]
Olá,

Gostei muito do seu plugin de integração e posso dizer que é bem mais eficiente do que um que já foi utilizado por um cliente meu, que inclusive é pago, código bem limpo e organizado.

Fiz 2 pull request para pequenos ajustes que achei importante.

Um é uma questão simples de visualização no painel do pedido para que a pessoa só veja os detalhes do pagamento de cartão caso o pedido tenha usado esta opção de pagamento, isso evita confusão com quem cuida do processamento dos pedidos.

[Tela admin](https://github.com/marcos-alexandre82/integration-rede-for-woocommerce/pull/7)

A outra é pois nem sempre usar parcelas fixas na configuração é útil então coloquei um filtro assim da para estender essa função via código para quem quiser usar o plugin, tipo analisando dados do carrinho de compras ou mesmo do perfil do cliente logado.

[Parcelas dinamicas](https://github.com/marcos-alexandre82/integration-rede-for-woocommerce/pull/6)

**Comment by marcos-alexandre82** [comment]
@kaoecoito obrigado pelas contribuições ;)
Estou testando alguns outros ajustes e devo publicar uma nova versão com eles já implementados!
