### ISSUE TITLE
Erro na ultima atualização

### ISSUE THREAD

**Issue by kaoecoito** [marcos-alexandre82/integration-rede-for-woocommerce#9]
Boa tarde,

  Como estou testando a implementação de uma loja nova estou revisando bastante o código para ver algumas funcionalidades que preciso, vi que na ultima atualização 2.0.2 você menciona uma correção de id mas acredito que esta errado.

Era assim
`$wc_order = new WC_Order( $order->get_id() );`

Você mudou para
`$wc_order = new WC_Order( $order_id );`

Só que não existe esta variável $order_id, ela não foi declara nesse ponto, acredito que o que desejava era mudar para
`$wc_order = new WC_Order( $order->ID );`

Nesse ponto o objeto que você tem é o post do wordpress que é o objeto WP_Post onde o id é um atributo ID em maiúsculo.

**Comment by marcos-alexandre82** [comment]
@kaoecoito corrigido na próxima versão ;)
